
const CART_KEY='shrkawy_cart';
const ORDER_KEY='shrkawy_order';
function getCart(){try{return JSON.parse(localStorage.getItem(CART_KEY))||[]}catch{return[]}}
function saveCart(cart){localStorage.setItem(CART_KEY,JSON.stringify(cart));updateCartCount()}
function formatMoney(n){return new Intl.NumberFormat('ar-EG',{style:'currency',currency:'EGP',maximumFractionDigits:0}).format(n)}
function getProduct(id){return (window.PRODUCTS||[]).find(p=>p.id===Number(id))}
function updateCartCount(){const count=getCart().reduce((s,i)=>s+i.qty,0);document.querySelectorAll('.cart-count').forEach(e=>e.textContent=count)}
function showToast(message){const t=document.getElementById('toast');if(!t)return;t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function addToCart(id,qty=1){const p=getProduct(id);if(!p)return;const cart=getCart();const found=cart.find(i=>i.id===p.id);if(found)found.qty=Math.min(found.qty+Number(qty),p.stock);else cart.push({id:p.id,qty:Math.min(Number(qty),p.stock)});saveCart(cart);showToast('تمت إضافة المنتج إلى السلة')}
function cardHTML(p){return `<article class="card product-card"><div class="image-wrap"><img src="${p.image}" alt="${p.name}"></div><div class="product-info"><div class="meta-row"><span class="badge">${p.category}</span><span>⭐ ${p.rating}</span></div><h3>${p.name}</h3><p class="muted">${p.short}</p><div class="price-row"><div><span class="price">${formatMoney(p.price)}</span> <span class="old-price">${formatMoney(p.original)}</span></div><span class="discount">-${p.discount}%</span></div><div class="stock-row"><span class="${p.stock<10?'stock-low':'stock-ok'}">${p.stock<10?'كمية محدودة':'متوفر في المخزون'}</span><small class="muted">${p.stock} قطعة</small></div><div class="product-actions"><a class="btn btn-outline" href="product-details.html?id=${p.id}">عرض التفاصيل</a><button class="btn btn-primary" onclick="addToCart(${p.id})">أضف إلى السلة</button></div></div></article>`}
function renderProducts(){const all=document.getElementById('all-products'), featured=document.getElementById('featured-products');if(all)all.innerHTML=PRODUCTS.map(cardHTML).join('');if(featured)featured.innerHTML=PRODUCTS.slice(0,3).map(cardHTML).join('')}
function renderDetails(){const el=document.getElementById('product-details');if(!el)return;const id=new URLSearchParams(location.search).get('id')||1,p=getProduct(id);if(!p){el.innerHTML='<div class="empty">المنتج غير موجود.</div>';return}el.innerHTML=`<div class="card details-image"><img src="${p.image}" alt="${p.name}"></div><div class="card details-content"><span class="badge">${p.brand}</span><h1 style="font-size:2.2rem">${p.name}</h1><p class="lead">${p.description}</p><div class="price-row"><div><span class="price">${formatMoney(p.price)}</span> <span class="old-price">${formatMoney(p.original)}</span></div><span class="discount">خصم ${p.discount}%</span></div><p>⭐ ${p.rating} / 5</p><h3>المواصفات الفنية</h3><ul class="spec-list">${p.specs.map(s=>`<li>✓ ${s}</li>`).join('')}</ul><p><strong>الألوان:</strong> ${p.colors.join(' - ')}</p><p><strong>المخزون:</strong> ${p.stock} قطعة | <strong>الضمان:</strong> ${p.warranty}</p><p><strong>التوصيل:</strong> ${p.delivery}</p><p><strong>الإرجاع:</strong> خلال 14 يومًا بشرط سلامة المنتج وملحقاته.</p><div class="quantity"><label for="detail-qty">الكمية:</label><input id="detail-qty" type="number" min="1" max="${p.stock}" value="1"></div><button class="btn btn-primary" onclick="addToCart(${p.id},document.getElementById('detail-qty').value)">أضف إلى السلة</button></div>`}
function totals(cart){const subtotal=cart.reduce((s,i)=>{const p=getProduct(i.id);return s+(p?p.price*i.qty:0)},0);const shipping=subtotal===0?0:(subtotal>=2500?0:75);const discount=subtotal>=5000?Math.round(subtotal*.05):0;return{subtotal,shipping,discount,total:subtotal+shipping-discount}}
function renderCart(){const items=document.getElementById('cart-items'),sum=document.getElementById('cart-summary');if(!items||!sum)return;let cart=getCart();if(!cart.length&&new URLSearchParams(location.search).get('demo')==='1'){cart=[{id:1,qty:1},{id:3,qty:2}];saveCart(cart)}if(!cart.length){items.innerHTML='<div class="card empty"><h2>السلة فارغة</h2><p class="muted">أضف بعض المنتجات ثم عُد لإكمال الطلب.</p><a class="btn btn-primary" href="products.html">تصفح المنتجات</a></div>';sum.innerHTML='<h2>ملخص الطلب</h2><p class="muted">لا توجد منتجات.</p>';return}items.innerHTML=cart.map(i=>{const p=getProduct(i.id);return `<article class="card cart-item"><img src="${p.image}" alt="${p.name}"><div><h3>${p.name}</h3><div class="muted">سعر الوحدة: ${formatMoney(p.price)}</div><div class="qty-controls"><button class="qty-btn" onclick="changeQty(${p.id},1)">+</button><strong>${i.qty}</strong><button class="qty-btn" onclick="changeQty(${p.id},-1)">-</button></div></div><div><strong>${formatMoney(p.price*i.qty)}</strong><br><button class="btn btn-danger" onclick="removeItem(${p.id})">حذف</button></div></article>`}).join('');const t=totals(cart);sum.innerHTML=`<h2>ملخص الطلب</h2><div class="summary-line"><span>إجمالي المنتجات</span><strong>${formatMoney(t.subtotal)}</strong></div><div class="summary-line"><span>الشحن</span><strong>${t.shipping?formatMoney(t.shipping):'مجاني'}</strong></div><div class="summary-line"><span>الخصم</span><strong>-${formatMoney(t.discount)}</strong></div><div class="summary-line summary-total"><span>الإجمالي النهائي</span><strong>${formatMoney(t.total)}</strong></div><div class="actions"><a class="btn btn-outline" href="products.html">متابعة التسوق</a><button class="btn btn-danger" onclick="clearCart()">تفريغ السلة</button><a class="btn btn-primary" style="width:100%" href="checkout.html">الانتقال إلى الدفع</a></div>`}
function changeQty(id,delta){const cart=getCart(),i=cart.find(x=>x.id===id),p=getProduct(id);if(!i||!p)return;i.qty=Math.max(1,Math.min(p.stock,i.qty+delta));saveCart(cart);renderCart()}
function removeItem(id){saveCart(getCart().filter(i=>i.id!==id));renderCart()}
function clearCart(){if(confirm('هل تريد تفريغ السلة؟')){saveCart([]);renderCart()}}
document.addEventListener('DOMContentLoaded',()=>{document.querySelector('.menu-btn')?.addEventListener('click',()=>document.querySelector('.nav-links')?.classList.toggle('open'));updateCartCount();renderProducts();renderDetails();renderCart()});
